### PR TITLE
Update Readme.

### PR DESCRIPTION
**Pull request by Gregliest**
I thought this might be helpful to update now, but feel free to ignore pending the discussion in https://github.com/SciML/SciMLBenchmarks.jl/issues/285 if you prefer.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This is going to get immediately overwritten by the bot.

**Comment by Gregliest** [comment]
Oh, can you point me to the bot?

**Comment by ChrisRackauckas** [comment]
It's the CI scripts. https://github.com/SciML/SciMLBenchmarks.jl/tree/master/.buildkite

Specifically, https://github.com/SciML/SciMLBenchmarks.jl/blob/master/.buildkite/publish_benchmark_output.sh copies the built artifacts from the benchmark repo to here. IIRC, it copies the README as well. That might not be the best idea? Though, this repo isn't made for people to find, so maybe that should be made clear in the README for it.

**Comment by Gregliest** [comment]
Cool, thanks for clarifying. I do think it seems a little unexpected for the README from a different repo to be copied into this one, that has a slightly different purpose. Also, in a quick look through that folder I don't see where it would be copying the README, but I probably missed it. 

What do you mean by "this repo isn't made for people to find." Do you mean that we don't want people to find it, or that we should make it easier to find? 

Anyway, just let me know what you'd like me to do here (if anything).

**Comment by ChrisRackauckas** [comment]
I guess, let's see if it gets the update you made to the other README? If it doesn't update, then yeah it's not part of the auto-updating and we should change this README to be more specialized to this repo.

**Comment by Gregliest** [comment]
@ChrisRackauckas It doesn't look like the README got copied from the other repo.

**Comment by ChrisRackauckas** [comment]
Cool

**Pull request merged**
